"""야생CCTV: 30 curated stories (batch 1).

Every shot is a real camera-trap capture from Snapshot Serengeti (capture id
SEASON#SITE#ROLL#CAPTURE). Captions were written after looking at every frame;
stats come from the Snapshot Serengeti v2.1 annotations (2,659,222 captures,
225 cameras). Facts are kept to widely documented ones.

Beat keys: shot / use (frame subset) / focus (normalized box) / cam
(drift|push|pull|punch|hold|pan_lr|pan_rl|fit) / text ({} = yellow) / trans
(cut|static|flash|fade|rewind|whoosh) / sfx / fx (shake|flash|circle|freeze) /
callout / kind (card|grid) / big / small / dur / loop / zmax / notime.
"""


def S(cid, use=None, focus=None):
    return {"cap": cid, "use": use, "focus": focus}


def card(big, small="", bg=None, dur=None, **kw):
    b = {"kind": "card", "big": big, "small": small, "shot": bg}
    b["dur"] = dur or max(2.4, min(4.2, 1.2 + 0.055 * len(small)))
    b.update(kw)
    return b


def call(label, at=0.3, **kw):
    d = {"label": label, "at": at}
    d.update(kw)
    return d


P = "탄자니아 세렝게티 국립공원"

STORIES = [
    # 01 ------------------------------------------------------------
    dict(slug="buffalo_vs_lions", title=["물소 한 마리 vs", "{사자 무리} 추격전"], mood="suspense",
         yt_title="물소 한 마리 vs 사자 무리, 무인카메라에 찍힌 새벽 추격전 ㄷㄷ",
         desc="새벽 6시 59분, 먼지를 일으키며 달아나는 물소와 그 뒤를 쫓는 암사자들. 세렝게티 무인카메라 E02가 찍은 실제 연속 사진입니다.",
         tags=["사자", "물소", "사냥", "추격전"], animal="사자 무리와 아프리카 물소",
         pin="물소는 살아남았을까요? 여러분의 예상을 댓글로 남겨주세요!",
         beats=[
             dict(shot=S("SER_S11#E02#1#863", [0]), cam="punch", zmax=1.8, focus=[0.62, 0.26, 0.99, 0.52],
                  text="새벽 7시, 물소가 {전력으로} 달리고 있다", fx=["shake"], sfx=["impact"]),
             dict(shot=S("SER_S11#E02#1#863", [0]), cam="pull", zmax=1.8, focus=[0.04, 0.35, 0.42, 0.52],
                  text="그런데 그 뒤를 보면...", fx=["circle"], circle_at=0.8, sfx=["riser@-0.2"]),
             dict(shot=S("SER_S11#E02#1#863", [1, 2]), cam="hold", zmax=1.6, focus=[0.15, 0.3, 0.9, 0.55],
                  text="먼지 속에서 {암사자들}이 쫓아온다", callout=call("암사자"), sfx=["heartbeat:2.5"]),
             dict(shot=S("SER_S11#E02#1#865"), cam="drift", trans="static",
                  text="3분 뒤, 사자 두 마리가 {돌아왔다}"),
             dict(shot=S("SER_S11#E02#1#866"), cam="push", text="숨을 고르며 {카메라 앞}을 지나간다"),
             dict(shot=S("SER_S11#E02#1#867"), cam="hold", text="그런데 물소는 {어디에도} 보이지 않았다"),
             card("{4번 중 3번}은 실패", "사자의 사냥 성공률은 25% 안팎으로 알려져 있다. 물소는 사자를 죽이기도 하는 상대다",
                  bg=S("SER_S11#E02#1#863")),
             dict(shot=S("SER_S11#E02#1#869"), cam="push", trans="static",
                  text="1시간 뒤, 한 마리가 {카메라 쪽으로} 걸어왔다"),
             dict(shot=S("SER_S11#E02#1#871"), cam="pan_lr", trans="static",
                  text="4시간 뒤, 그 자리엔 {가젤과 얼룩말}이 돌아왔다"),
             dict(shot=S("SER_S11#E02#1#878"), cam="drift", text="아무 일도 {없었다는 듯이}"),
             dict(shot=S("SER_S11#E02#1#863", [0]), cam="hold", zmax=1.5, focus=[0.62, 0.3, 0.98, 0.62], fx=["freeze"],
                  text="이 물소는 {살아남았을까}?", sfx=["ding"]),
         ]),
    # 02 ------------------------------------------------------------
    dict(slug="lion_meets_camera", title=["카메라를 발견한", "{수사자들}의 반응"], mood="suspense",
         yt_title="무인카메라를 발견한 수사자들의 반응 ㄷㄷ",
         desc="렌즈에 갈기가 닿을 만큼 다가온 수사자부터 새벽 실루엣까지. 세렝게티 무인카메라에 찍힌 수사자 모음입니다.",
         tags=["사자", "수사자", "갈기"], animal="수사자",
         pin="갈기가 짙은 수사자가 더 인기가 많다는 사실, 알고 계셨나요?",
         beats=[
             dict(shot=S("SER_S2#O09#1#119", [2]), cam="punch", zmax=1.4, text="카메라 화면이 {갈기}로 가득 찼다",
                  fx=["shake"], sfx=["impact"]),
             dict(shot=S("SER_S2#O09#1#119"), cam="drift", trans="rewind", loop=0.55,
                  text="냄새를 맡는 듯 {렌즈 앞}을 떠나지 않는다"),
             dict(shot=S("SER_S2#P11#3#54"), cam="push", trans="static",
                  text="2주 뒤 다른 카메라, 또 {수사자}다", callout=call("수사자", at=0.6)),
             dict(shot=S("SER_S2#P11#3#95"), cam="hold", text="이번엔 아예 {카메라 옆}에 자리를 잡았다"),
             dict(shot=S("SER_S2#P11#3#255"), cam="drift", trans="static",
                  text="두 달 뒤, 같은 카메라 앞을 {성큼성큼}"),
             card("갈기 색의 비밀", "세렝게티 사자 연구에 따르면 갈기가 짙을수록 나이가 많고 힘이 세며 암사자에게 더 인기가 많다",
                  bg=S("SER_S2#P11#3#54")),
             dict(shot=S("SER_S3#U10#12#37"), cam="pan_lr", trans="flash",
                  text="새벽 7시, {실루엣}만 남기고 사라진 수사자"),
             dict(shot=S("SER_S2#O09#1#119", [1]), cam="hold", zmax=1.3, fx=["freeze"],
                  text="이 카메라, {무사했을까}?", sfx=["ding"]),
         ]),
    # 03 ------------------------------------------------------------
    dict(slug="savanna_fire", title=["불길이 {카메라를}", "덮쳤다"], mood="suspense",
         yt_title="초원에 불이 났을 때 무인카메라에 찍힌 것 (그리고 두 달 뒤)",
         desc="2015년 8월 23일 오후 2시 22분, 세렝게티 초원의 불길이 무인카메라 B09 앞을 지나갔습니다. 카메라는 그 뒤 두 달 동안의 변화까지 모두 기록했습니다.",
         tags=["초원화재", "산불", "사바나", "자연"], animal="사바나 초원 화재",
         pin="불이 지나간 뒤 두 달 만에 초원이 어떻게 변했는지 끝까지 확인해 보세요!",
         beats=[
             dict(shot=S("SER_S11#B09#1#146", [1]), cam="punch", zmax=1.35, focus=[0.1, 0.55, 0.9, 0.95],
                  text="초원 한가운데 {불길}이 치솟았다", cap="top", fx=["shake"], sfx=["impact", "fire:3"]),
             dict(shot=S("SER_S11#B09#1#138"), cam="drift", trans="rewind",
                  text="2시간 전만 해도 {평화로운} 초원이었다",
                  callout=call("가젤", at=0.9, pos=[0.43, 0.43])),
             dict(shot=S("SER_S11#B09#1#143"), cam="drift", loop=0.5, text="오후 2시, 카메라가 {이유 없이} 계속 찍히기 시작했다"),
             dict(shot=S("SER_S11#B09#1#145"), cam="push", zmax=1.3, focus=[0.2, 0.4, 0.8, 0.8],
                  text="그리고 1분 뒤...", sfx=["riser@0.2", "heartbeat:1.8"]),
             dict(shot=S("SER_S11#B09#1#146"), cam="punch", zmax=1.3, focus=[0.1, 0.55, 0.9, 0.95], loop=0.45,
                  text="14시 22분, {불길}이 카메라 앞까지 왔다", cap="top", fx=["shake", "flash"], sfx=["impact", "fire:3"]),
             dict(shot=S("SER_S11#B09#1#147"), cam="push", zmax=1.3, focus=[0.2, 0.5, 0.9, 0.95], loop=0.45,
                  text="풀이 타는 소리만 {가득하다}", cap="top", sfx=["fire:2.5"]),
             dict(shot=S("SER_S11#B09#1#161"), cam="drift", trans="static", text="20분 뒤, 모든 게 {까맣게} 탔다"),
             dict(shot=S("SER_S11#B09#1#353"), cam="push", zmax=1.4, focus=[0.1, 0.3, 0.9, 0.5], trans="fade",
                  text="밤이 되자 불길은 {지평선}을 따라 번졌다"),
             dict(shot=S("SER_S11#B09#1#383"), cam="drift", text="카메라는 밤늦게까지 이 장면을 {찍고 있었다}"),
             dict(shot=S("SER_S11#B09#1#501"), cam="drift", trans="static", text="다음 날 아침, 초원은 {검은 들판}이 됐다"),
             dict(shot=S("SER_S11#B09#1#1297"), cam="hold", zmax=2.4, focus=[0.3, 0.33, 0.7, 0.43], trans="static",
                  text="그런데 이틀 뒤, {누군가} 돌아왔다", fx=["circle"], circle_at=1.0),
             dict(shot=S("SER_S11#B09#2#3200"), cam="drift", trans="flash",
                  text="그리고 두 달 뒤, 초원은 {초록빛}으로 돌아왔다", sfx=["ding"]),
             card("불은 끝이 아니다", "불탄 자리에는 새싹이 돋고, 초식동물들이 그 새싹을 먹으러 모여든다",
                  bg=S("SER_S11#B09#2#3200")),
             dict(shot=S("SER_S11#B09#1#146", [2]), cam="hold", zmax=1.2, focus=[0.1, 0.55, 0.9, 0.95],
                  text="초원에게 불은 {새로운 시작}이다", cap="top"),
         ]),
    # 04 ------------------------------------------------------------
    dict(slug="hyena_face_camera", title=["한밤중 카메라에", "{얼굴을 들이민} 녀석"], mood="suspense", amb="night",
         yt_title="한밤중 무인카메라에 얼굴을 들이민 동물의 정체 ㄷㄷ",
         desc="밤 8시 24분, 세렝게티 무인카메라에 하얀 얼굴이 들이닥쳤습니다. 적외선 카메라에 찍힌 점박이하이에나입니다.",
         tags=["하이에나", "점박이하이에나", "야간카메라"], animal="점박이하이에나",
         pin="하이에나가 청소부라는 건 오해라는 사실, 알고 계셨나요?",
         beats=[
             dict(shot=S("SER_S2#O12#2#1390", [2]), cam="punch", zmax=1.3,
                  text="밤 8시 24분, 카메라에 {하얀 얼굴}이 들이닥쳤다", fx=["shake"], sfx=["impact"]),
             dict(shot=S("SER_S2#O12#2#1390", [0]), cam="push", zmax=1.4, trans="rewind",
                  text="처음엔 {킁킁} 냄새만 맡더니"),
             dict(shot=S("SER_S2#O12#2#1390", [1]), cam="punch", zmax=1.3,
                  text="{렌즈에 코를} 박을 듯이 다가왔다", fx=["shake"], sfx=["impact"]),
             dict(shot=S("SER_S2#O12#2#1390", [2]), cam="hold", zmax=1.2,
                  text="정체는 바로 {점박이하이에나}", callout=call("점박이하이에나", pos=[0.5, 0.2])),
             card("사자보다 센 턱", "뼈까지 부숴 먹는 턱 힘. 무는 힘이 사자보다 세다고 알려져 있다",
                  bg=S("SER_S2#O12#2#1390")),
             dict(shot=S("SER_S1#M12#1#33"), cam="drift", text="밤이 되면 초원의 {진짜 주인}이 된다"),
             dict(shot=S("SER_S5#M10#2#292"), cam="drift", trans="static", text="낮에도 카메라 앞을 {아무렇지 않게}"),
             card("청소부라는 오해", "하이에나는 먹이의 상당 부분을 직접 사냥하는 사냥꾼이다", bg=S("SER_S9#J05#2#424")),
             dict(shot=S("SER_S9#J05#2#424"), cam="push", text="무리 지어 다니는 {사냥꾼}"),
             dict(shot=S("SER_S2#O12#2#1390", [1]), cam="hold", zmax=1.3, fx=["freeze"],
                  text="무인카메라는 하이에나에게 {물어뜯기는} 일이 종종 있다", sfx=["ding"]),
         ]),
    # 05 ------------------------------------------------------------
    dict(slug="leopard_rubs_camera", title=["카메라에 몸을 비빈", "{표범}"], mood="mystery",
         yt_title="무인카메라에 몸을 비빈 표범 (266만 번 중 410번 찍힌 동물)",
         desc="세렝게티 무인카메라 225대가 266만 번 셔터를 누르는 동안 표범은 단 410번 찍혔습니다. 그중 카메라에 가장 가까이 온 표범들입니다.",
         tags=["표범", "레오파드", "맹수"], animal="표범",
         pin="266만 번 중 410번. 표범을 카메라에 담는 게 얼마나 어려운지 느껴지시나요?",
         beats=[
             dict(shot=S("SER_S5#T08#3#69", [0]), cam="punch", zmax=1.3,
                  text="카메라 화면이 {점무늬}로 덮였다", fx=["shake"], sfx=["impact"]),
             dict(shot=S("SER_S5#T08#3#69", [1, 2]), cam="drift", loop=0.6, text="몸을 {비비며} 지나가는 이 녀석은"),
             card("266만 번 중 {410번}", "세렝게티 무인카메라 225대가 찍은 266만 번 중 표범이 찍힌 횟수",
                  bg=S("SER_S5#T08#3#69")),
             dict(shot=S("SER_S5#O08#3#19"), cam="drift", trans="static",
                  text="같은 날 다른 카메라, 이번엔 {바로 앞}에 누웠다"),
             dict(shot=S("SER_S5#J02#1#594"), cam="punch", text="그리고 이 녀석은 카메라를 {정면으로} 쳐다봤다",
                  callout=call("표범", at=0.5), sfx=["whoosh@-0.15"]),
             card("나무 위의 사냥꾼", "표범은 자기보다 무거운 먹이도 나무 위로 끌고 올라간다. 사자와 하이에나에게 뺏기지 않기 위해서다",
                  bg=S("SER_S5#J02#1#594")),
             dict(shot=S("SER_S6#U11#2#148"), cam="push", trans="static", text="밤이 되면 {소리 없이} 움직인다"),
             dict(shot=S("SER_S2#I12#3#62"), cam="hold", text="그래서 가장 {보기 힘든} 맹수로 불린다"),
             dict(shot=S("SER_S5#J02#1#594", [2]), cam="hold", fx=["freeze"],
                  text="오늘 밤에도 누군가를 {지켜보고} 있을지 모른다"),
         ]),
    # 06 ------------------------------------------------------------
    dict(slug="lion_cub_dawn", title=["새벽 카메라에 찍힌", "{아기 사자}"], mood="cute",
         yt_title="새벽 무인카메라를 빤히 쳐다보는 아기 사자 🦁",
         desc="새벽 6시 47분, 바위 위에 앉아 카메라를 빤히 쳐다보는 아기 사자. 세렝게티 무인카메라에 찍힌 아기 사자들입니다.",
         tags=["아기사자", "사자", "귀여운동물"], animal="아기 사자",
         pin="이 아기 사자, 지금은 멋진 어른 사자가 되어 있을까요?",
         beats=[
             dict(shot=S("SER_S8#J09#3#338", [2]), cam="punch", zmax=1.8, focus=[0.78, 0.38, 1.0, 0.76],
                  text="새벽 6시 47분, 카메라가 {누군가}를 포착했다", sfx=["pop"]),
             dict(shot=S("SER_S8#J09#3#338"), cam="pull", zmax=2.2, focus=[0.82, 0.4, 1.0, 0.56], loop=0.6,
                  text="나무 위에서 카메라를 {빤히} 쳐다보는", callout=call("아기 사자", at=0.4)),
             dict(shot=S("SER_S8#J09#3#338", [1]), cam="hold", zmax=2.4, focus=[0.82, 0.4, 1.0, 0.56],
                  text="{아기 사자}다", sfx=["ding"]),
             dict(shot=S("SER_S2#E09#3#69"), cam="drift", trans="static", text="밤에는 엄마 곁에 {꼭 붙어} 있다"),
             dict(shot=S("SER_S9#J09#1#33"), cam="push", text="엄마 등에 {올라타기도} 하고"),
             dict(shot=S("SER_S2#P11#3#244"), cam="drift", text="엄마를 {졸졸} 따라다닌다"),
             card("절반가량", "야생에서 태어난 아기 사자의 절반가량은 첫해를 넘기지 못한다",
                  bg=S("SER_S8#J09#3#338")),
             dict(shot=S("SER_S8#J09#3#338", [0]), cam="hold", zmax=1.6, focus=[0.78, 0.38, 1.0, 0.76],
                  text="그래서 이 사진이 더 {소중하다}"),
             dict(shot=S("SER_S8#J09#3#338", [2]), cam="hold", zmax=2.4, focus=[0.82, 0.4, 1.0, 0.56], fx=["freeze"],
                  text="이 아기 사자, 지금은 {어른}이 됐을까?"),
         ]),
    # 07 ------------------------------------------------------------
    dict(slug="black_rhino", title=["0.003% 확률로 찍힌", "{검은코뿔소}"], mood="mystery",
         yt_title="266만 번 중 71번, 무인카메라에 찍힌 검은코뿔소",
         desc="세렝게티 무인카메라가 266만 번 촬영하는 동안 코뿔소는 단 71번 찍혔습니다. 멸종위기 위급 등급, 검은코뿔소입니다.",
         tags=["코뿔소", "검은코뿔소", "멸종위기동물"], animal="검은코뿔소",
         pin="전 세계에 약 6천 마리만 남은 검은코뿔소. 이 녀석이 오늘도 무사하길 바랍니다.",
         beats=[
             dict(shot=S("SER_S2#F12#1#124"), cam="punch", text="새벽 2시 37분, 카메라 앞에 {뿔 두 개}",
                  fx=["shake"], sfx=["impact"]),
             card("266만 번 중 {71번}", "세렝게티 무인카메라에 코뿔소가 찍힌 횟수. 확률로는 약 0.003%",
                  bg=S("SER_S2#F12#1#124")),
             dict(shot=S("SER_S2#F12#1#124"), cam="hold", text="정체는 멸종위기 {검은코뿔소}",
                  callout=call("검은코뿔소", at=0.4)),
             dict(shot=S("SER_S2#G12#3#132"), cam="push", trans="static", text="4개월 뒤, 옆 카메라에도 {코뿔소}가 나타났다"),
             dict(shot=S("SER_S2#G12#3#133"), cam="hold", text="1분 뒤, 카메라 쪽으로 {고개를} 돌린다"),
             dict(shot=S("SER_S2#G12#3#160"), cam="push", trans="static",
                  text="6일 뒤 오후 5시, 같은 카메라에 {다시}"),
             dict(shot=S("SER_S2#G12#3#161"), cam="push", text="점점 {다가오더니}", sfx=["heartbeat:2"]),
             dict(shot=S("SER_S2#G12#3#162"), cam="punch", text="{렌즈 코앞}까지 왔다", fx=["shake"], sfx=["impact"]),
             card("전 세계 약 6천 마리", "뿔을 노린 밀렵 때문에 멸종위기 '위급' 등급이 된 검은코뿔소",
                  bg=S("SER_S2#G12#3#162")),
             dict(shot=S("SER_S2#G12#3#163"), cam="drift", text="그런데 그 뿔은 사람 {손톱}과 같은 성분이다"),
             dict(shot=S("SER_S2#G12#3#162", [2]), cam="hold", fx=["freeze"], text="이 녀석이 오늘도 {무사하길}"),
         ]),
    # 08 ------------------------------------------------------------
    dict(slug="hyena_follows", title=["맹수가 지나가면", "{2분 뒤} 나타나는 녀석"], mood="suspense", amb="night",
         yt_title="맹수가 지나가면 꼭 2분 뒤에 나타나는 동물 (무인카메라 기록)",
         desc="표범, 치타, 사자가 지나간 자리에 몇 분 뒤면 어김없이 나타나는 동물. 세렝게티 무인카메라 기록을 시간순으로 비교했습니다.",
         tags=["하이에나", "표범", "치타", "사자"], animal="점박이하이에나",
         pin="표범 90초, 사자 2분, 치타 3분. 하이에나는 대체 어떻게 알고 오는 걸까요?",
         beats=[
             dict(shot=S("SER_S3#M08#12#455"), cam="punch", text="어둠 속에서 {눈}이 빛났다", fx=["shake"],
                  sfx=["impact"]),
             dict(shot=S("SER_S3#M08#12#454"), cam="drift", trans="rewind",
                  text="2분 전, 이곳을 지나간 건 {암사자}였다", callout=call("암사자", at=0.6)),
             dict(shot=S("SER_S3#M08#12#455"), cam="push", text="그리고 2분 뒤 나타난 {하이에나} 무리",
                  callout=call("하이에나", at=0.6)),
             dict(shot=S("SER_S7#B03#2#311"), cam="drift", trans="static", text="다른 날 밤, 이번엔 {표범}이 지나가고"),
             dict(shot=S("SER_S7#B03#2#312"), cam="push", text="정확히 {90초} 뒤, 또 하이에나", sfx=["ding"]),
             dict(shot=S("SER_S2#H07#3#1559"), cam="drift", trans="static", text="낮에도 마찬가지. {치타}가 쉬던 자리에"),
             dict(shot=S("SER_S2#H07#3#1560"), cam="push", text="3분 뒤, 하이에나가 {냄새를} 맡으며 나타났다"),
             card("뺏는 게 더 쉽다", "하이에나는 다른 맹수의 먹이를 빼앗는 걸로 유명하다. 치타와 표범은 사냥감을 자주 뺏긴다",
                  bg=S("SER_S2#H07#3#1560")),
             dict(shot=S("SER_S2#G02#3#93"), cam="drift", trans="static", text="사자 무리가 지나간 밤에도"),
             dict(shot=S("SER_S2#G02#3#95"), cam="push", text="어김없이 {하이에나}가 뒤따랐다"),
             dict(shot=S("SER_S5#M10#2#292", [0]), cam="hold", fx=["freeze"], text="세렝게티 맹수들의 {그림자}"),
         ]),
    # 09 ------------------------------------------------------------
    dict(slug="cheetah_family", title=["카메라 앞에서", "{육아 중}인 치타"], mood="cute",
         yt_title="무인카메라 앞에서 육아 중인 치타 가족 (아기 치타 등털의 비밀)",
         desc="세렝게티 무인카메라에 찍힌 치타 엄마와 새끼들. 아기 치타의 복슬복슬한 등털에는 생존 전략이 숨어 있습니다.",
         tags=["치타", "아기치타", "귀여운동물"], animal="치타 가족",
         pin="세렝게티에서 아기 치타가 어른이 될 확률은 약 5%. 이 아이들이 무사히 자랐기를!",
         beats=[
             dict(shot=S("SER_S11#J05#1#76", [2]), cam="punch", text="누가 카메라를 {올려다}보고 있다", sfx=["pop"]),
             dict(shot=S("SER_S11#J05#1#76"), cam="drift", loop=0.6,
                  text="엄마 치타 옆에 붙어 있는 {아기 치타}", callout=call("아기 치타", at=0.5)),
             dict(shot=S("SER_S1#L10#1#74"), cam="push", trans="static", focus=[0.32, 0.2, 0.62, 0.9],
                  text="등에 난 {복슬복슬한 털} 보이시나요?", fx=["circle"], circle_at=0.8),
             card("벌꿀오소리 흉내?", "아기 치타의 등털이 사나운 벌꿀오소리처럼 보이게 해서 천적을 피한다는 가설이 있다",
                  bg=S("SER_S1#L10#1#74")),
             dict(shot=S("SER_S2#H08#2#42"), cam="drift", loop=0.55, trans="static", text="엄마는 {하품} 중"),
             dict(shot=S("SER_S2#M09#3#95"), cam="drift", text="새끼들은 엄마 곁을 {떠나지 않는다}"),
             dict(shot=S("SER_S1#L10#1#33"), cam="push", text="한 가족이 {카메라 앞}에서 쉬어간다"),
             card("약 5%", "세렝게티에서 아기 치타가 어른이 될 확률. 사자와 하이에나가 가장 큰 위협이다",
                  bg=S("SER_S2#M09#3#95")),
             dict(shot=S("SER_S1#I13#1#158"), cam="punch", trans="static",
                  text="그래서 엄마의 눈빛은 늘 {경계 중}이다"),
             dict(shot=S("SER_S11#J05#1#76", [2]), cam="hold", fx=["freeze"], text="이 아이들이 {무사히} 자랐기를"),
         ]),
    # 10 ------------------------------------------------------------
    dict(slug="giraffe_legs", title=["기린을 찍으려 했는데", "{다리만} 찍혔다"], mood="funny",
         yt_title="무인카메라로 기린을 찍으면 생기는 일 ㅋㅋ",
         desc="세렝게티 무인카메라의 최대 난적은 기린입니다. 카메라 높이에선 다리밖에 안 보이거든요.",
         tags=["기린", "웃긴동물", "동물"], animal="기린",
         pin="기린 다리 길이만 약 1.8m. 여러분 키보다 긴가요?",
         beats=[
             dict(shot=S("SER_S6#S09#1#524", [0]), cam="punch", zmax=1.25, text="카메라 앞에 {거대한 다리}가 나타났다",
                  sfx=["impact"]),
             dict(shot=S("SER_S6#S09#1#524", [1, 2]), cam="drift",
                  text="성큼... 성큼... {카메라를 넘어갔다}", sfx=["whoosh@1.1"]),
             dict(shot=S("SER_S5#F04#2#894"), cam="drift", trans="static", text="다른 카메라도 {다리}"),
             dict(shot=S("SER_S5#C10#1#561"), cam="drift", trans="static", text="이것도 {다리}", dur=1.8),
             dict(shot=S("SER_S2#N08#2#8"), cam="drift", trans="static", text="또 {다리}...", dur=1.8, sfx=["scratch"]),
             card("다리 길이 약 1.8m", "기린 다리는 웬만한 사람 키보다 길다. 카메라 높이에선 다리밖에 안 보이는 이유",
                  bg=S("SER_S2#N08#2#8")),
             dict(shot=S("SER_S5#P03#3#6", [1]), cam="drift", trans="static", text="심지어 {꼬리}까지"),
             dict(shot=S("SER_S5#B09#1#228"), cam="drift", trans="flash", text="그러다 드디어... {얼굴 공개}",
                  sfx=["ding"]),
             dict(shot=S("SER_S5#C09#1#527"), cam="push", trans="static", text="멀리 떨어져야 겨우 {전신}이 찍힌다"),
             card("심장 무게 약 11kg", "머리 끝까지 피를 올려 보내려면 이만한 심장이 필요하다", bg=S("SER_S5#B09#1#228")),
             dict(shot=S("SER_S6#S09#1#524", [0]), cam="hold", zmax=1.2, text="세렝게티 카메라의 {최대 난적}, 기린"),
         ]),
    # 11 ------------------------------------------------------------
    dict(slug="serval_ears", title=["사자보다 사냥을 잘하는", "{귀 큰 고양이}"], mood="mystery", amb="night",
         yt_title="사자보다 사냥 성공률이 높은 고양이, 서벌 (야간 무인카메라)",
         desc="밤 8시 49분, 어둠 속에 거대한 귀가 나타났습니다. 몸에 비해 귀가 가장 큰 고양이, 서벌입니다.",
         tags=["서벌", "고양이", "야생고양이"], animal="서벌",
         pin="서벌의 사냥 성공률은 약 50%. 사자의 두 배 수준입니다!",
         beats=[
             dict(shot=S("SER_S1#G13#1#9", [0]), cam="punch", text="어둠 속에 {거대한 귀}가 나타났다", fx=["shake"],
                  sfx=["impact"]),
             dict(shot=S("SER_S1#G13#1#9", [1]), cam="hold", text="카메라를 {빤히} 쳐다보다가"),
             dict(shot=S("SER_S1#G13#1#9", [2]), cam="hold", text="휙 {돌아선다}", sfx=["whoosh@-0.1"]),
             dict(shot=S("SER_S2#D09#3#357"), cam="push", trans="flash",
                  text="정체는 {서벌}, 몸에 비해 귀가 가장 큰 고양이", callout=call("서벌", at=0.5)),
             card("사냥 성공률 약 50%", "사자는 약 25%. 서벌은 두 번에 한 번꼴로 사냥에 성공한다", bg=S("SER_S2#D09#3#357")),
             dict(shot=S("SER_S2#I09#3#551"), cam="push", trans="static", text="풀숲의 쥐가 내는 {작은 소리}까지 듣고"),
             dict(shot=S("SER_S4#I10#2#1211"), cam="drift", text="높이 뛰어올라 {위에서} 덮친다"),
             dict(shot=S("SER_S2#N10#1#21"), cam="drift", trans="static", text="그리고 카메라엔 {귀만} 남기고 사라졌다"),
             dict(shot=S("SER_S1#G13#1#9", [0]), cam="hold", fx=["freeze"], text="세렝게티 밤의 {레이더}, 서벌"),
         ]),
    # 12 ------------------------------------------------------------
    dict(slug="one_spot_6months", title=["초원 한 자리에 카메라를", "{6개월} 두었더니"], mood="epic",
         yt_title="초원 한 자리에 카메라를 6개월 두었더니 찍힌 동물 19종",
         desc="2012년 5월부터 12월까지 세렝게티 무인카메라 P03 한 대에 찍힌 동물들을 날짜순으로 모았습니다.",
         tags=["야생동물", "동물모음", "사파리"], animal="카메라 P03에 찍힌 19종",
         pin="여러분이 가장 보고 싶었던 동물은 몇 번째에 나왔나요?",
         beats=[
             dict(kind="grid", dur=2.6, text="카메라 한 대에 찍힌 동물 {19종}", sfx=["impact@0.1"], items=[
                 {"shot": S("SER_S5#P03#3#705"), "label": "표범"}, {"shot": S("SER_S5#P03#1#83"), "label": "치타"},
                 {"shot": S("SER_S5#P03#3#1027"), "label": "코끼리"}, {"shot": S("SER_S5#P03#1#111"), "label": "카라칼"},
                 {"shot": S("SER_S5#P03#3#515"), "label": "물소"}, {"shot": S("SER_S5#P03#3#596"), "label": "개코원숭이"},
                 {"shot": S("SER_S5#P03#2#55"), "label": "얼룩말"}, {"shot": S("SER_S5#P03#3#2345"), "label": "하이에나"},
                 {"shot": S("SER_S5#P03#3#896"), "label": "비서새"}]),
             dict(shot=S("SER_S5#P03#1#4"), cam="drift", trans="rewind", text="2012년 5월, 무인카메라 {P03} 설치"),
             dict(shot=S("SER_S5#P03#1#50"), cam="drift", trans="static", text="6월, 코앞까지 온 {혹멧돼지}", dur=2.0),
             dict(shot=S("SER_S5#P03#1#56"), cam="push", trans="static", text="밤에는 작은 영양 {딕딕}", dur=2.0),
             dict(shot=S("SER_S5#P03#1#83"), cam="drift", trans="static", text="7월, 카메라를 가린 {치타}", dur=2.0,
                  sfx=["impact"]),
             dict(shot=S("SER_S5#P03#1#89"), cam="drift", trans="static", text="같은 날 저녁 {하테비스트}", dur=1.9),
             dict(shot=S("SER_S5#P03#1#111"), cam="drift", trans="static", text="8월 아침, {카라칼}", dur=1.9),
             dict(shot=S("SER_S5#P03#2#46"), cam="hold", trans="static", text="9월, 한밤의 {토피}", dur=1.8),
             dict(shot=S("SER_S5#P03#2#55"), cam="hold", trans="static", text="{얼룩말}", dur=1.6),
             dict(shot=S("SER_S5#P03#3#6"), cam="drift", trans="static", text="10월, {기린}의 다리", dur=1.8),
             dict(shot=S("SER_S5#P03#3#515"), cam="hold", trans="static", text="11월, {아프리카 물소}", dur=1.8),
             dict(shot=S("SER_S5#P03#3#596"), cam="hold", trans="static", text="카메라를 들여다보는 {개코원숭이}", dur=2.0),
             dict(shot=S("SER_S5#P03#3#705"), cam="push", trans="static", text="그리고 밤엔 {표범}까지!", dur=2.2,
                  fx=["shake"], sfx=["impact"]),
             dict(shot=S("SER_S5#P03#3#880"), cam="drift", trans="static", text="세상에서 가장 큰 영양 {일런드}", dur=2.0),
             dict(shot=S("SER_S5#P03#3#896"), cam="drift", trans="static", text="뱀 사냥꾼 {비서새}", dur=1.8),
             dict(shot=S("SER_S5#P03#3#1027"), cam="hold", trans="static", text="해 질 녘 {코끼리}", dur=1.8),
             dict(shot=S("SER_S5#P03#3#1076"), cam="drift", trans="static", text="누 떼의 {대이동}", dur=1.8),
             dict(shot=S("SER_S5#P03#3#2345"), cam="push", trans="static", text="그리고 {하이에나}까지", dur=2.0),
             dict(kind="grid", dur=3.0, text="여러분의 {최애}는?", items=[
                 {"shot": S("SER_S5#P03#1#50"), "label": "혹멧돼지"}, {"shot": S("SER_S5#P03#1#89"), "label": "하테비스트"},
                 {"shot": S("SER_S5#P03#2#46"), "label": "토피"}, {"shot": S("SER_S5#P03#3#880"), "label": "일런드"},
                 {"shot": S("SER_S5#P03#3#1076"), "label": "누"}, {"shot": S("SER_S5#P03#3#6"), "label": "기린"},
                 {"shot": S("SER_S5#P03#1#56"), "label": "딕딕"}, {"shot": S("SER_S5#P03#3#908"), "label": "타조"},
                 {"shot": S("SER_S5#P03#3#705"), "label": "표범"}]),
         ]),
    # 13 ------------------------------------------------------------
    dict(slug="honey_badger", title=["세상에서 가장", "{겁 없는} 동물"], mood="funny",
         yt_title="누 떼 앞을 당당하게 걸어가는 세상에서 가장 겁 없는 동물",
         desc="기네스북에 '세상에서 가장 겁 없는 동물'로 올랐던 벌꿀오소리가 세렝게티 무인카메라에 찍혔습니다.",
         tags=["벌꿀오소리", "겁없는동물", "허니배저"], animal="벌꿀오소리",
         pin="크기는 강아지만 한데 사자에게도 덤비는 벌꿀오소리. 진짜 최강자는 누구일까요?",
         beats=[
             dict(shot=S("SER_S8#P08#2#553", [1], [0.72, 0.36, 0.99, 0.64]), cam="punch", zmax=2.2, text="누 떼 앞을 {당당하게} 걸어가는 이 녀석",
                  sfx=["impact"]),
             dict(shot=S("SER_S8#P08#2#553", None, [0.72, 0.36, 0.99, 0.64]), cam="drift", zmax=2.2, loop=0.6, text="크기는 {강아지}만 한데",
                  callout=call("벌꿀오소리", at=0.4)),
             card("기네스북 공인", "'세상에서 가장 겁 없는 동물'로 기네스북에 올랐던 벌꿀오소리", bg=S("SER_S8#P08#2#553")),
             dict(shot=S("SER_S1#G13#1#12", None, [0.3, 0.72, 0.65, 0.98]), cam="push", trans="static", text="덩치 큰 맹수에게도 {덤벼드는} 성격"),
             dict(shot=S("SER_S8#J13#1#371", None, [0.28, 0.68, 0.66, 0.9]), cam="push", trans="static",
                  text="가죽이 {헐렁해서} 물려도 몸을 돌려 반격한다"),
             card("독사도 버틴다", "뱀독에 대한 저항력이 있어 코브라를 사냥하기도 한다", bg=S("SER_S8#J13#1#371")),
             dict(shot=S("SER_S1#H06#3#123"), cam="push", zmax=2.4, trans="static",
                  text="좋아하는 음식은 {벌집 속 애벌레}"),
             dict(shot=S("SER_S8#P08#2#553", [2], [0.72, 0.36, 0.99, 0.64]), cam="hold", zmax=2.2, fx=["freeze"],
                  text="세렝게티 진짜 {최강자}는 이 녀석일지도"),
         ]),
    # 14 ------------------------------------------------------------
    dict(slug="elephant_trunk", title=["코끼리가 카메라를", "{코로} 확인했다"], mood="funny",
         yt_title="코끼리가 무인카메라를 발견하면 하는 행동",
         desc="세렝게티 무인카메라 앞에 길쭉한 무언가가 나타났습니다. 카메라를 검사하러 온 코끼리 코입니다.",
         tags=["코끼리", "코끼리코", "동물행동"], animal="아프리카코끼리",
         pin="코끼리의 호기심, 귀엽다 vs 무섭다?",
         beats=[
             dict(shot=S("SER_S1#H08#1#39", [1]), cam="punch", text="카메라 앞에 {길쭉한 뭔가}가 나타났다",
                  sfx=["impact"]),
             dict(shot=S("SER_S1#H08#1#39"), cam="drift", loop=0.55, text="킁킁... 코로 {카메라를} 살피는 중"),
             dict(shot=S("SER_S1#H08#1#39", [2]), cam="pull", text="정체는 {코끼리 코}", callout=call("코끼리 코", at=0.6)),
             card("근육 4만 개 이상", "코끼리 코에는 뼈가 없다. 대신 수만 개의 근육으로 움직인다", bg=S("SER_S1#H08#1#39")),
             dict(shot=S("SER_S6#D10#2#74"), cam="hold", trans="static", text="밤에도 {카메라 검사}는 계속된다"),
             dict(shot=S("SER_S2#F12#1#86"), cam="drift", trans="static", text="코에 물을 한 번에 약 {8리터}까지 담는다"),
             dict(shot=S("SER_S6#B03#2#225"), cam="drift", trans="static", text="그리고 발 한번 {잘못} 디디면...",
                  sfx=["heartbeat:2"]),
             dict(shot=S("SER_S5#P03#3#1027"), cam="hold", trans="static", text="카메라는 늘 {목숨 걸고} 찍는다"),
             dict(shot=S("SER_S1#H08#1#39", [1]), cam="hold", fx=["freeze"], text="코끼리의 호기심, {귀엽다} vs {무섭다}?"),
         ]),
    # 15 ------------------------------------------------------------
    dict(slug="warthog_sniff", title=["카메라 냄새를 맡은", "{품바}"], mood="funny",
         yt_title="무인카메라 냄새를 맡는 품바 (혹멧돼지) ㅋㅋ",
         desc="화면 가득 콧구멍이 나타났습니다. 라이온킹 품바의 실제 모델, 혹멧돼지가 세렝게티 무인카메라를 검사하는 모습입니다.",
         tags=["품바", "혹멧돼지", "라이온킹"], animal="혹멧돼지",
         pin="하쿠나 마타타! 품바가 무릎 꿇고 밥 먹는 이유, 알고 계셨나요?",
         beats=[
             dict(shot=S("SER_S5#F02#1#58", [0]), cam="punch", zmax=1.2, text="화면 가득 {정체불명의 얼굴}이 나타났다",
                  sfx=["impact"]),
             dict(shot=S("SER_S5#F02#1#58", [0, 1]), cam="drift", loop=0.45, text="킁킁킁... {카메라 냄새} 확인 중"),
             dict(shot=S("SER_S5#F02#1#58", [2]), cam="drift", text="확인 끝, 쿨하게 {퇴장}", sfx=["whoosh@0.1"]),
             dict(shot=S("SER_S3#G04#11#64"), cam="push", trans="static",
                  text="정체는 라이온킹 {품바}의 실제 모델, 혹멧돼지", callout=call("혹멧돼지", at=0.5)),
             card("무릎 꿇고 식사", "목이 짧아서 무릎을 꿇고 풀을 뜯는다. 그래서 무릎에 굳은살이 있다", bg=S("SER_S3#G04#11#64")),
             dict(shot=S("SER_S3#G13#11#15"), cam="drift", trans="static", text="도망칠 땐 꼬리를 {안테나처럼} 세운다"),
             card("뒷걸음으로 들어가는 집", "땅돼지가 판 굴에 엉덩이부터 들어간다. 나올 때 엄니로 바로 맞서기 위해서다",
                  bg=S("SER_S3#G13#11#15")),
             dict(shot=S("SER_S5#F02#1#58", [0]), cam="hold", zmax=1.2, fx=["freeze"], text="{하쿠나 마타타}",
                  sfx=["ding"]),
         ]),
    # 16 ------------------------------------------------------------
    dict(slug="great_migration", title=["150만 마리가", "{카메라 앞을} 지나가면"], mood="epic",
         yt_title="누 150만 마리가 무인카메라 앞을 지나가면 (세렝게티 대이동)",
         desc="매년 비를 따라 세렝게티를 도는 누 떼 대이동. 무인카메라 앞을 지나간 행렬과 그 뒤를 노리는 눈까지 담았습니다.",
         tags=["누떼", "대이동", "세렝게티대이동"], animal="누 떼",
         pin="마지막 장면, 누 떼 뒤에 숨어 있던 사냥꾼 보셨나요?",
         beats=[
             dict(shot=S("SER_S8#B13#1#157"), cam="pan_lr", notime=True, text="지평선이 {움직이기} 시작했다",
                  sfx=["impact"]),
             dict(shot=S("SER_S3#T09#12#154"), cam="drift", trans="static", text="{누 떼 대이동}이 시작됐다"),
             dict(shot=S("SER_S8#P03#2#231"), cam="pan_rl", trans="static", text="끝이 보이지 않는 {행렬}"),
             card("약 150만 마리", "누 약 150만 마리와 얼룩말, 가젤 수십만 마리가 비를 따라 1년 내내 이동한다",
                  bg=S("SER_S8#P03#2#231")),
             dict(shot=S("SER_S10#M06#2#275"), cam="drift", trans="static", text="카메라 바로 옆으로도 {쉴 새 없이}"),
             dict(shot=S("SER_S11#S09#2#270"), cam="pan_lr", trans="static", text="하루에도 {수십 km}를 걷는다"),
             card("하루 약 8천 마리", "새끼가 태어나는 시기에는 하루에 약 8천 마리의 아기 누가 태어난다", bg=S("SER_S7#U09#1#23")),
             dict(shot=S("SER_S7#U09#1#23"), cam="push", zmax=1.8, trans="static",
                  text="갓 태어난 새끼도 {몇 분 만에} 일어나 걷는다"),
             dict(shot=S("SER_S7#U09#1#25"), cam="punch", zmax=2.0, focus=[0.1, 0.8, 0.42, 1.0],
                  text="그리고 8분 뒤, 그 뒤를 {노리는 눈}", callout=call("치타", at=0.6), sfx=["impact"]),
             dict(shot=S("SER_S3#T09#12#154", [2]), cam="hold", fx=["freeze"], text="세렝게티에서 가장 {위대한} 여행"),
         ]),
    # 17 ------------------------------------------------------------
    dict(slug="porcupine_quills", title=["사자도 건드리지 못하는", "{가시 괴물}"], mood="mystery", amb="night",
         yt_title="사자도 함부로 못 건드리는 가시 동물의 정체 (야간 무인카메라)",
         desc="밤 8시, 세렝게티 무인카메라 앞에서 가시가 폭발하듯 펼쳐졌습니다. 아프리카 호저입니다.",
         tags=["호저", "고슴도치", "가시"], animal="아프리카 호저",
         pin="호저가 가시를 쏜다는 건 오해! 진짜 무기는 뒷걸음 돌진입니다.",
         beats=[
             dict(shot=S("SER_S1#D12#1#28", [2]), cam="punch", zmax=1.3, text="밤 8시, 카메라 앞에서 {가시}가 폭발했다",
                  fx=["shake"], sfx=["impact"]),
             dict(shot=S("SER_S1#D12#1#28"), cam="drift", loop=0.5, trans="rewind", text="가시를 {부채처럼} 펼친 이 녀석은"),
             dict(shot=S("SER_S6#J05#1#84"), cam="push", trans="static", text="정체는 아프리카 {호저}",
                  callout=call("호저", at=0.8)),
             card("가시를 쏜다?", "흔한 오해다. 가시를 날리지는 못한다. 대신 쉽게 빠져서 상대 몸에 박힌다", bg=S("SER_S1#D12#1#28")),
             dict(shot=S("SER_S2#K09#1#5"), cam="drift", trans="static", text="위협을 느끼면 {뒷걸음으로} 돌진한다",
                  fx=["shake"], sfx=["whoosh"]),
             dict(shot=S("SER_S5#O12#2#121"), cam="push", trans="static", text="그래서 사자도 {함부로} 덤비지 않는다"),
             card("사자의 악몽", "가시에 찔린 상처가 곪아 사냥을 못 하게 된 사자의 사례도 있다", bg=S("SER_S5#O12#2#121")),
             dict(shot=S("SER_S2#I05#3#17"), cam="push", trans="static", text="가장 긴 가시는 {30cm}가 넘는다"),
             dict(shot=S("SER_S9#J05#2#18"), cam="push", trans="fade", text="노을 속 {가시 실루엣}"),
             dict(shot=S("SER_S1#D12#1#28", [2]), cam="hold", fx=["freeze"], text="초원에서 {건드리면 안 되는} 동물 1순위"),
         ]),
    # 18 ------------------------------------------------------------
    dict(slug="ostrich_kick", title=["사자도 발차기 한 방에", "{쓰러뜨리는} 새"], mood="epic",
         yt_title="사자도 발차기 한 방에 쓰러뜨리는 새 (타조의 진실)",
         desc="먹구름 아래 나타난 거대한 실루엣. 세상에서 가장 큰 새, 타조가 세렝게티 무인카메라에 찍혔습니다.",
         tags=["타조", "새", "동물상식"], animal="타조",
         pin="타조가 위험하면 머리를 모래에 묻는다는 말, 사실이 아닙니다!",
         beats=[
             dict(shot=S("SER_S2#I05#2#11", [2]), cam="punch", text="먹구름 아래 {거대한 실루엣}", sfx=["impact"]),
             dict(shot=S("SER_S2#I05#2#11"), cam="drift", loop=0.6, text="키 약 2.5m, 세상에서 {가장 큰 새}",
                  callout=call("타조", at=0.5)),
             dict(shot=S("SER_S3#H07#12#197"), cam="push", trans="static", text="진짜 무기는 이 {다리}",
                  fx=["circle"], circle_at=0.7),
             card("시속 70km", "날지 못하는 대신 두 다리로 시속 70km까지 달린다", bg=S("SER_S3#O07#12#309")),
             dict(shot=S("SER_S3#O07#12#309"), cam="drift", trans="static", text="발차기 한 번이면 {사자}도 크게 다친다"),
             dict(shot=S("SER_S3#M06#11#123", None, [0.25, 0.0, 0.95, 0.95]), cam="drift", trans="static",
                  text="긴 목으로 {두리번두리번}"),
             card("눈 > 뇌", "타조의 눈은 뇌보다 크다", bg=S("SER_S3#M06#11#123"), dur=2.4),
             dict(shot=S("SER_S3#F04#11#107"), cam="drift", trans="static",
                  text="위험하면 머리를 모래에 묻는다? {사실이 아니다}"),
             dict(shot=S("SER_S2#I05#2#11", [2]), cam="hold", fx=["freeze"], text="세렝게티의 {육상 선수}, 타조"),
         ]),
    # 19 ------------------------------------------------------------
    dict(slug="hippo_night", title=["밤이 되면", "{물 밖으로} 나오는 하마"], mood="mystery", amb="night",
         yt_title="밤이 되면 물 밖으로 나오는 하마 (야간 무인카메라)",
         desc="새벽 3시 39분, 세렝게티 무인카메라 앞에 분홍빛 거대한 몸이 나타났습니다. 밤마다 풀을 뜯으러 나오는 하마입니다.",
         tags=["하마", "야간카메라", "위험한동물"], animal="하마",
         pin="하마가 헤엄을 못 친다는 사실, 알고 계셨나요?",
         beats=[
             dict(shot=S("SER_S2#F06#3#26"), cam="punch", zmax=1.3, text="새벽 3시 39분, {분홍빛} 거대한 몸",
                  fx=["shake"], sfx=["impact"]),
             dict(shot=S("SER_S5#C05#3#37", None, [0.6, 0.05, 1.0, 0.95]), cam="push", zmax=1.5, trans="static", text="정체는 {하마}",
                  callout=call("하마", at=0.5)),
             card("헤엄을 못 친다", "하마는 물에 뜨지 못한다. 물속 바닥을 걷거나 뛰어서 이동한다", bg=S("SER_S5#C05#3#37")),
             dict(shot=S("SER_S5#E05#4#176"), cam="push", trans="static", text="밤마다 물 밖으로 나와 {풀을 뜯는다}"),
             card("하룻밤 약 40kg", "해가 지면 몇 km를 걸어 다니며 풀을 먹는다", bg=S("SER_S5#E05#4#176")),
             dict(shot=S("SER_S6#B13#2#19"), cam="drift", trans="static", text="혼자가 아니다. {무리 전체}가 올라온다"),
             dict(shot=S("SER_S5#D04#3#201"), cam="push", trans="static", text="짧은 거리는 시속 {30km}로 달린다"),
             card("가장 위험한 동물", "아프리카에서 사람을 가장 많이 해치는 대형 동물 중 하나가 하마다", bg=S("SER_S2#F06#3#26")),
             dict(shot=S("SER_S2#F06#3#26"), cam="hold", zmax=1.2, fx=["freeze"],
                  text="밤의 초원에서 {절대 마주치면 안 되는} 동물"),
         ]),
    # 20 ------------------------------------------------------------
    dict(slug="baby_elephant", title=["아기 코끼리가", "{엄마 곁}을 떠나지 않는 이유"], mood="cute",
         yt_title="무인카메라에 찍힌 아기 코끼리 (엄마 배 밑 시점 주의)",
         desc="엄마 옆에 꼭 붙어 있는 아기 코끼리와 가족들. 세렝게티 무인카메라에 찍힌 코끼리 가족입니다.",
         tags=["아기코끼리", "코끼리", "귀여운동물"], animal="아기 코끼리",
         pin="코끼리 임신 기간은 약 22개월. 육지 동물 중 가장 깁니다!",
         beats=[
             dict(shot=S("SER_S10#I06#1#11", [2]), cam="punch", text="엄마 옆에 {꼭 붙어} 있는 아기 코끼리",
                  sfx=["pop"]),
             dict(shot=S("SER_S10#I06#1#11"), cam="drift", loop=0.6, text="태어날 때 몸무게가 약 {100kg}",
                  callout=call("아기 코끼리", at=0.5)),
             card("임신 기간 약 22개월", "육지 동물 중 가장 길다", bg=S("SER_S10#I06#1#11"), dur=2.4),
             dict(shot=S("SER_S7#P13#1#554"), cam="drift", trans="static", text="카메라가 {엄마 배 밑}을 찍었다"),
             dict(shot=S("SER_S6#O11#2#233"), cam="push", trans="static", text="아직 코 쓰는 법이 {서툴다}"),
             card("코 사용법은 연습", "아기 코끼리는 몇 달 동안 코를 흔들고 빨면서 쓰는 법을 배운다", bg=S("SER_S6#O11#2#233")),
             dict(shot=S("SER_S8#O11#2#103"), cam="pan_lr", trans="static", text="무리는 새끼를 {가운데} 두고 걷는다"),
             dict(shot=S("SER_S5#H01#2#77"), cam="push", trans="static", text="엄마, 이모, 언니들이 {함께} 키운다"),
             dict(shot=S("SER_S10#I06#1#11", [0]), cam="hold", fx=["freeze"], text="세렝게티에서 가장 {든든한} 가족"),
         ]),
    # 21 ------------------------------------------------------------
    dict(slug="lion_pride", title=["카메라가 {사자 무리}", "한가운데 떨어졌다"], mood="funny",
         yt_title="무인카메라가 사자 무리 한가운데 떨어지면 생기는 일",
         desc="눈을 떠보니 사자 무리 한가운데. 세렝게티 무인카메라에 찍힌 사자 무리의 일상입니다.",
         tags=["사자", "사자무리", "암사자"], animal="사자 무리",
         pin="사자는 하루 최대 20시간을 쉰다는 사실! 여러분의 하루와 비교하면?",
         beats=[
             dict(shot=S("SER_S1#F10#1#153", [1]), cam="punch", zmax=1.3, text="눈을 떠보니 {사자 무리} 한가운데",
                  sfx=["impact"]),
             dict(shot=S("SER_S1#F10#1#153", [0]), cam="drift", text="다들 {자는 중}..."),
             dict(shot=S("SER_S1#F10#1#153", [2]), cam="hold", text="한 마리가 {고개를 든다}", sfx=["heartbeat:2"]),
             card("하루 20시간", "사자는 하루 최대 20시간을 쉬거나 잔다. 사냥할 힘을 아끼기 위해서다", bg=S("SER_S1#F10#1#153")),
             dict(shot=S("SER_S1#I13#1#114"), cam="drift", trans="static", text="사냥은 대부분 {암사자}의 몫"),
             dict(shot=S("SER_S5#M09#1#236", [0], [0.03, 0.54, 0.18, 0.74]), cam="punch", zmax=2.6, trans="static",
                  text="그런데 갑자기 {으르렁}!", fx=["shake"], sfx=["impact"]),
             dict(shot=S("SER_S5#M09#1#236", [0], [0.21, 0.47, 0.34, 0.68]), cam="push", zmax=2.6,
                  text="목에 찬 건 연구팀의 {추적 목걸이}", fx=["circle"], circle_at=0.6),
             dict(shot=S("SER_S5#M09#1#242"), cam="drift", trans="static", text="배부르면 다시 {꿀잠}"),
             dict(shot=S("SER_S1#E13#1#113"), cam="drift", trans="static", text="그런데 카메라는 {신경도 안 쓴다}"),
             dict(shot=S("SER_S1#F10#1#153", [2]), cam="hold", zmax=1.2, fx=["freeze"],
                  text="여러분이 이 카메라라면 {버틸 수} 있나요?"),
         ]),
    # 22 ------------------------------------------------------------
    dict(slug="secretary_bird", title=["뱀을 {발차기}로", "잡는 새"], mood="epic",
         yt_title="뱀을 발차기로 잡는 새, 비서새 (무인카메라)",
         desc="깃털 왕관을 쓴 새가 세렝게티 무인카메라 앞을 지나갔습니다. 발차기로 뱀을 사냥하는 비서새입니다.",
         tags=["비서새", "새", "뱀"], animal="비서새",
         pin="발이 뱀에 닿는 시간 0.015초. 눈으로는 볼 수 없는 속도입니다!",
         beats=[
             dict(shot=S("SER_S3#C07#11#141", [0]), cam="punch", text="카메라 앞에 {깃털 왕관}을 쓴 새",
                  sfx=["impact"]),
             dict(shot=S("SER_S3#C07#11#141"), cam="drift", loop=0.55, text="긴 다리로 {성큼성큼}"),
             dict(shot=S("SER_S5#R07#1#217"), cam="push", trans="static", text="이름은 {비서새}",
                  callout=call("비서새", at=0.4)),
             card("0.015초", "뱀을 내려찍을 때 발이 닿는 시간. 힘은 몸무게의 약 5배", bg=S("SER_S5#R07#1#217")),
             dict(shot=S("SER_S5#E09#1#77"), cam="push", trans="static", text="독사도 {발차기}로 기절시킨다"),
             card("왜 비서새?", "머리 뒤 깃털이 옛날 서기가 귀에 꽂은 깃펜 같아서라는 설이 있다", bg=S("SER_S5#E09#1#77")),
             dict(shot=S("SER_S5#G13#2#24"), cam="drift", trans="static", text="하루에 수십 km를 {걸으며} 사냥한다"),
             dict(shot=S("SER_S5#P03#3#896"), cam="drift", trans="static", text="초원의 {킥복서}"),
             dict(shot=S("SER_S5#R07#1#217", [2]), cam="hold", fx=["freeze"], text="세렝게티에서 가장 {패셔너블한} 사냥꾼"),
         ]),
    # 23 ------------------------------------------------------------
    dict(slug="caracal_jump", title=["3m를 뛰어올라", "{새를 잡는} 고양이"], mood="mystery",
         yt_title="3m를 뛰어올라 새를 잡는 고양이, 카라칼 (무인카메라)",
         desc="귀 끝에 검은 털 뭉치가 달린 고양이, 카라칼이 세렝게티 무인카메라에 찍혔습니다. 먹이를 물고 가는 모습까지 포착됐습니다.",
         tags=["카라칼", "고양이", "야생고양이"], animal="카라칼",
         pin="카라칼이라는 이름은 '검은 귀'라는 뜻이에요!",
         beats=[
             dict(shot=S("SER_S9#K11#2#310", None, [0.72, 0.5, 0.95, 0.75]), cam="punch", zmax=2.4, text="귀 끝에 {검은 털 뭉치}",
                  sfx=["impact"]),
             dict(shot=S("SER_S9#K11#2#310", None, [0.5, 0.48, 0.95, 0.99]), cam="pull", zmax=1.6, text="정체는 {카라칼}",
                  callout=call("카라칼", at=0.8)),
             dict(shot=S("SER_S1#J12#1#11"), cam="drift", loop=0.6, trans="static", text="밤에도 {귀를 쫑긋}"),
             card("점프 약 3m", "날아오르는 새를 공중에서 낚아챌 만큼 높이 뛴다", bg=S("SER_S1#J12#1#11")),
             dict(shot=S("SER_S2#I04#1#190"), cam="push", trans="static", text="새벽 6시, 입에 {뭔가} 물려 있다",
                  fx=["circle"], circle_at=0.9),
             dict(shot=S("SER_S5#P03#1#111"), cam="push", zmax=2.2, trans="static", text="황금빛 초원을 지나가는 {사냥꾼}"),
             card("검은 귀", "카라칼이라는 이름은 튀르키예어 '카라쿨락', 검은 귀에서 왔다", bg=S("SER_S5#P03#1#111")),
             dict(shot=S("SER_S3#H11#11#30"), cam="push", trans="static", text="옛날엔 새 사냥용으로 {길들이기}도 했다"),
             dict(shot=S("SER_S9#K11#2#310", None, [0.72, 0.5, 0.95, 0.75]), cam="hold", zmax=2.2, fx=["freeze"],
                  text="고양이계 {점프 챔피언}"),
         ]),
    # 24 ------------------------------------------------------------
    dict(slug="aardvark", title=["돼지가 아닌데", "{땅돼지}라 불리는 동물"], mood="mystery", amb="night",
         yt_title="돼지가 아닌데 땅돼지라 불리는 동물 (새벽 3시 무인카메라)",
         desc="토끼 같은 귀, 돼지 같은 코, 캥거루 같은 꼬리. 밤에만 움직여 보기 힘든 땅돼지가 세렝게티 무인카메라에 찍혔습니다.",
         tags=["땅돼지", "개미핥기", "야행성동물"], animal="땅돼지",
         pin="땅돼지가 판 굴은 다른 동물들의 집이 됩니다. 초원의 건축가!",
         beats=[
             dict(shot=S("SER_S1#E10#1#217", [1]), cam="punch", text="새벽 3시, 카메라 앞을 {휙} 지나간 것",
                  sfx=["whoosh@-0.15", "impact"]),
             dict(shot=S("SER_S1#E10#1#217"), cam="drift", loop=0.5,
                  text="토끼 같은 귀, 돼지 같은 코, {캥거루 같은} 꼬리"),
             dict(shot=S("SER_S1#L03#1#42"), cam="push", trans="static", text="정체는 {땅돼지}",
                  callout=call("땅돼지", at=0.5)),
             card("하룻밤 5만 마리", "개미와 흰개미를 하룻밤에 최대 5만 마리까지 먹는다", bg=S("SER_S1#L03#1#42")),
             dict(shot=S("SER_S1#L03#1#154"), cam="push", trans="static", text="혀 길이만 약 {30cm}"),
             card("초원의 건축가", "땅돼지가 판 굴은 혹멧돼지, 하이에나, 호저 같은 동물들의 집이 된다", bg=S("SER_S1#L03#1#154")),
             dict(shot=S("SER_S2#G06#1#164"), cam="drift", trans="static", text="밤에만 움직여서 {보기 힘든} 동물"),
             dict(shot=S("SER_S1#L03#1#42", [1]), cam="hold", fx=["freeze"], text="이름의 뜻은 {땅의 돼지}"),
         ]),
    # 25 ------------------------------------------------------------
    dict(slug="zebra_hug", title=["얼룩말이 서로", "{목을 기대는} 이유"], mood="cute",
         yt_title="얼룩말이 서로 목을 기대는 이유 (무인카메라)",
         desc="세렝게티 무인카메라 앞에서 서로 목을 기대는 얼룩말들. 다정해 보이는 이 행동에는 이유가 있습니다.",
         tags=["얼룩말", "동물행동", "힐링"], animal="얼룩말",
         pin="얼룩말 줄무늬는 사람 지문처럼 모두 다르다는 사실!",
         beats=[
             dict(shot=S("SER_S8#O06#2#201"), cam="punch", text="카메라 앞에서 {포옹} 중인 얼룩말", sfx=["pop"]),
             dict(shot=S("SER_S2#R09#1#101"), cam="push", trans="static", text="엄마와 {아기 얼룩말}",
                  callout=call("아기", at=0.6)),
             card("서로 털 골라주기", "서로의 목과 등을 이빨로 긁어주며 유대감을 쌓는다", bg=S("SER_S2#R09#1#101")),
             dict(shot=S("SER_S8#B08#3#295"), cam="drift", trans="static", text="반대 방향을 보면 {사방을} 경계할 수 있다"),
             card("줄무늬 = 지문", "얼룩말의 줄무늬는 사람의 지문처럼 모두 다르다", bg=S("SER_S8#B08#3#295"), dur=2.6),
             dict(shot=S("SER_S4#Q05#2#94"), cam="drift", trans="static", text="줄무늬가 {흡혈 파리}를 쫓는다는 연구도 있다"),
             dict(shot=S("SER_S9#E06#3#1138"), cam="push", trans="static", text="그래서 늘 {함께} 다닌다"),
             dict(shot=S("SER_S2#R09#1#101", [2]), cam="hold", fx=["freeze"], text="세렝게티에서 가장 {다정한} 동물"),
         ]),
    # 26 ------------------------------------------------------------
    dict(slug="cape_buffalo", title=["사자도 무서워하는", "{검은 죽음}"], mood="suspense",
         yt_title="사자도 무서워하는 '검은 죽음'이 무인카메라를 막아섰다",
         desc="카메라 앞을 막아선 거대한 뿔. 사자도 함부로 덤비지 못하는 아프리카 물소입니다.",
         tags=["아프리카물소", "버팔로", "빅5"], animal="아프리카 물소",
         pin="사자 무리에게 쫓기던 물소 이야기는 사건파일 #01에서 확인하세요!",
         beats=[
             dict(shot=S("SER_S4#H06#1#22", [0]), cam="punch", zmax=1.3, text="카메라 앞을 막아선 {거대한 뿔}",
                  fx=["shake"], sfx=["impact"]),
             dict(shot=S("SER_S4#H06#1#22"), cam="drift", loop=0.6, text="눈빛부터 {예사롭지 않다}"),
             card("별명: 검은 죽음", "아프리카 물소는 사자도 함부로 덤비지 못하는 동물이다", bg=S("SER_S4#H06#1#22")),
             dict(shot=S("SER_S5#E03#2#87"), cam="drift", trans="static", text="무리가 공격받으면 {함께} 반격한다"),
             dict(shot=S("SER_S5#D05#1#340"), cam="push", trans="static", text="등 위의 새는 {진드기}를 먹는 소등쪼기새",
                  callout=call("소등쪼기새", at=0.6, pos=[0.52, 0.2])),
             dict(shot=S("SER_S5#C06#1#107"), cam="push", trans="static", text="밤에도 무리를 {지킨다}"),
             dict(shot=S("SER_S4#J01#1#265"), cam="drift", trans="static", text="빅5 중에서도 {가장 위험하다}는 말이 있다"),
             dict(shot=S("SER_S4#H06#1#22", [2]), cam="hold", zmax=1.3, fx=["freeze"],
                  text="사자 무리와의 추격전은 {사건파일 #01}에서"),
         ]),
    # 27 ------------------------------------------------------------
    dict(slug="bat_eared_fox", title=["귀가 얼굴보다", "{더 큰} 여우"], mood="cute", amb="night",
         yt_title="귀가 얼굴보다 큰 여우 (세렝게티 무인카메라)",
         desc="밤 10시, 카메라 앞에 귀가 먼저 도착했습니다. 큰 귀로 땅속 흰개미 소리를 듣는 큰귀여우입니다.",
         tags=["큰귀여우", "여우", "귀여운동물"], animal="큰귀여우",
         pin="이빨이 최대 50개! 큰귀여우는 이빨 부자입니다.",
         beats=[
             dict(shot=S("SER_S9#N06#3#303", None, [0.52, 0.66, 0.82, 0.96]), cam="punch", zmax=2.4,
                  text="밤 10시, 카메라 앞에 {귀가 먼저} 도착했다",
                  sfx=["pop"]),
             dict(shot=S("SER_S2#H07#2#853"), cam="drift", trans="static", text="낮에는 가족이 {함께} 산책",
                  callout=call("큰귀여우", at=0.6)),
             card("귀 길이 약 13cm", "큰 귀로 땅속 흰개미 소리를 듣고 체온도 식힌다", bg=S("SER_S2#H07#2#853")),
             dict(shot=S("SER_S9#M06#4#701"), cam="push", trans="static", text="여우인데 주식은 {흰개미}"),
             card("이빨 최대 50개", "포유류 중에서도 이빨이 아주 많은 편이다", bg=S("SER_S9#M06#4#701"), dur=2.6),
             dict(shot=S("SER_S8#M06#3#142"), cam="fit", trans="static", text="밤에도 {셋이서} 흰개미를 찾는다"),
             dict(shot=S("SER_S2#H07#2#853", [2]), cam="hold", fx=["freeze"], text="세렝게티 {귀여움} 담당"),
         ]),
    # 28 ------------------------------------------------------------
    dict(slug="zorilla_smell", title=["스컹크보다 지독한", "{냄새 폭탄}"], mood="funny", amb="night",
         yt_title="스컹크보다 지독한 냄새를 뿜는 동물 (야간 무인카메라)",
         desc="새벽 3시, 꼬리를 치켜든 수상한 녀석이 세렝게티 무인카메라에 찍혔습니다. 세상에서 가장 냄새가 지독한 동물로 꼽히는 조릴라입니다.",
         tags=["조릴라", "스컹크", "야행성동물"], animal="조릴라",
         pin="화면으로만 봐서 다행인 동물 1위!",
         beats=[
             dict(shot=S("SER_S1#K12#1#1358", [2]), cam="punch", text="새벽 3시, {꼬리를 치켜든} 수상한 녀석",
                  sfx=["impact"]),
             dict(shot=S("SER_S1#K12#1#1358"), cam="drift", loop=0.5, text="흑백 줄무늬에 {풍성한 꼬리}"),
             dict(shot=S("SER_S10#S08#1#558"), cam="push", trans="static", text="스컹크 같지만 {조릴라}다",
                  callout=call("조릴라", at=0.6)),
             card("냄새 주의", "위협을 느끼면 지독한 냄새의 액체를 뿜는다. 세상에서 가장 냄새가 지독한 동물로 꼽히기도 한다",
                  bg=S("SER_S10#S08#1#558")),
             dict(shot=S("SER_S9#M06#4#1236"), cam="push", trans="static", text="흑백 줄무늬는 {가까이 오지 마} 라는 경고"),
             dict(shot=S("SER_S5#Q11#3#297"), cam="push", trans="static", text="그래도 안 통하면 {죽은 척}을 한다"),
             dict(shot=S("SER_S1#K12#1#1358", [2]), cam="hold", fx=["freeze"], text="화면으로만 봐서 {다행}인 동물"),
         ]),
    # 29 ------------------------------------------------------------
    dict(slug="aardwolf", title=["하이에나인데", "{흰개미}만 먹는다"], mood="mystery", amb="night",
         yt_title="하이에나 가문인데 흰개미만 먹는 동물 (땅늑대)",
         desc="하이에나를 닮은 줄무늬 동물이 밤마다 세렝게티 무인카메라에 찍혔습니다. 고기 대신 흰개미를 먹는 땅늑대입니다.",
         tags=["땅늑대", "하이에나", "야행성동물"], animal="땅늑대",
         pin="하룻밤에 흰개미 20만 마리! 땅늑대의 반전 식성입니다.",
         beats=[
             dict(shot=S("SER_S3#N05#11#8"), cam="punch", text="하이에나를 닮은 {줄무늬} 동물", sfx=["impact"]),
             dict(shot=S("SER_S5#L04#1#393"), cam="push", trans="static", text="정체는 {땅늑대}",
                  callout=call("땅늑대", at=0.6)),
             card("하이에나과", "이름은 늑대지만 사실 하이에나과 동물이다", bg=S("SER_S5#L04#1#393"), dur=2.6),
             dict(shot=S("SER_S8#F03#2#82"), cam="push", trans="static", text="그런데 {고기}를 먹지 않는다"),
             card("하룻밤 20만 마리", "긴 혀로 흰개미를 핥아 먹는다. 하룻밤에 20만 마리가 넘기도 한다", bg=S("SER_S8#F03#2#82")),
             dict(shot=S("SER_S5#L04#1#456"), cam="push", zmax=2.6, trans="static", text="이빨도 {작은 못}처럼 작아졌다"),
             dict(shot=S("SER_S10#K11#1#522"), cam="push", zmax=2.4, trans="static",
                  text="밤에만 움직여서 {보기 힘들다}"),
             dict(shot=S("SER_S3#N05#11#8"), cam="hold", fx=["freeze"], text="하이에나 가문의 {반전 매력}"),
         ]),
    # 30 ------------------------------------------------------------
    dict(slug="baboon_camera", title=["카메라를 {만져본}", "개코원숭이"], mood="funny",
         yt_title="무인카메라를 만져본 개코원숭이 ㅋㅋ",
         desc="세렝게티 무인카메라 화면이 갑자기 흔들리기 시작했습니다. 범인은 호기심 많은 개코원숭이였습니다.",
         tags=["개코원숭이", "원숭이", "웃긴동물"], animal="개코원숭이",
         pin="카메라가 무사한 게 기적! 여러분 집에도 이런 호기심쟁이가 있나요?",
         beats=[
             dict(shot=S("SER_S6#K03#2#427", [1]), cam="punch", zmax=1.2, text="화면이 갑자기 {가려졌다}",
                  fx=["shake"], sfx=["impact"]),
             dict(shot=S("SER_S6#K03#2#427"), cam="drift", loop=0.5, text="누군가 카메라를 {만지고} 있다"),
             dict(shot=S("SER_S5#P03#3#596", [0, 1], [0.5, 0.5, 1.0, 0.95]), cam="push", zmax=1.8, trans="static",
                  text="범인은 바로 {개코원숭이}",
                  callout=call("개코원숭이", at=0.6)),
             card("호기심 대장", "개코원숭이는 영리하고 호기심이 많아 낯선 물건을 만져보고 뒤진다", bg=S("SER_S5#P03#3#596")),
             dict(shot=S("SER_S2#G03#2#193", [1, 2], [0.3, 0.45, 1.0, 0.98]), cam="drift", trans="static",
                  text="{새끼}를 데리고 나타난 가족"),
             dict(shot=S("SER_S6#K03#2#40"), cam="drift", trans="static", text="수십 마리가 {무리 지어} 산다"),
             dict(shot=S("SER_S2#E06#3#33"), cam="push", trans="static", text="그리고 다시 {카메라 확인}"),
             dict(shot=S("SER_S6#K03#2#427", [1]), cam="hold", zmax=1.2, fx=["freeze"], text="카메라가 {무사한 게} 기적"),
         ]),
]
